# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: librariz_development

test:
  <<: *default
  database: librariz_test

staging:
  <<: *default
  database: librariz_staging
  username: root
  password:

production:
  <<: *default
  database: librariz_production
  username: root
  password:
